services:
  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: enablegeek
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    ports:
      - "5332:5432"
    volumes:
      - db:/data/postgres
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:




